#!/usr/bin/env php
<?php

use App\Application;
use GuzzleHttp\Client;
use App\Commands\Parse;
use App\Services\UnzipService;
use App\Services\ParseService;
use App\Services\DownloadService;
use App\Services\FileWriterService;


require __DIR__ . '/vendor/autoload.php';

$app = new Application;
$download = new DownloadService(new Client());
$fileWriter = new FileWriterService();
$unzip = new UnzipService();
$parse =  new ParseService();

$app->add(new Parse(null,$download,$fileWriter,$unzip,$parse));

$app->run();


